### ISSUE TITLE
你好, 工程有问题啊, 缺少文件也没法选择模拟器.

### ISSUE THREAD

**Issue by shanbozhu** [GIKICoder/GRichLabel#3]
你好, 工程有问题啊, 缺少文件也没法选择模拟器.

**Comment by GIKICoder** [comment]
我用xcode 9 建的project .. 用xcode 9 以下的编译可能有问题. 可以用你的xcode 建一个工程. 把代码放上去.稍后我用xcode 8 改一下

**Comment by shanbozhu** [comment]
好的, 我试试.

**Comment by GIKICoder** [comment]
麻烦重新更新一下. 刚才少提交了文件.

**Comment by shanbozhu** [comment]
好的, 还是希望能支持xcode8, 方便更多朋友使用, 感谢.

**Comment by GIKICoder** [comment]
ok . 已经可以了.
