### ISSUE TITLE
支持带有图片表情的attributedString吗

### ISSUE THREAD

**Issue by wyt666** [GIKICoder/GRichLabel#4]

**Comment by wyt666** [comment]
attributedString里包含图片表情，如果我这样（self.richLabel.attributedString = [NSMutableAttributedString findAttrString:str font:[UIFont boldSystemFontOfSize:25]]; ）设置attributedString，图片表情显示不出来，请问有什么解决的办法吗？

**Comment by GIKICoder** [comment]
update 一下. 有部分debug 功能提交上去了.

**Comment by wyt666** [comment]
![7ede75c604af9954c37f7ea3aa522452](https://user-images.githubusercontent.com/15173846/32439097-cfac2eb0-c2b2-11e7-9044-18c94f122533.png)
这个图片是双击微信文字消息的效果图，他的这个表情是图片转成的NSMutableAttributedString。。。
我也把表情是图片转成的NSMutableAttributedString，赋值给self.richLabel.attributedString就是显示不出来！我刚才更新了一下还是显示不出来

**Comment by GIKICoder** [comment]
你把表情标签替换成runDelegate 对象了吗. 参考GAttributedStringFactory.m 中的 createAttributedStringWithAttributedConfig 函数

**Comment by wyt666** [comment]
哦，我用的是自己的方法，换成你这方法我再试试吧

**Comment by wyt666** [comment]
现在可以显示图片表情了，

现在还有个问题就是，这块代码怎么才能获取到‘’图片表情”对应的文字呢
- (NSString *)getSelectText
{
    return [self.attributedString.string substringWithRange:NSMakeRange(_selectedRange.location, _selectedRange.length)];
}

**Comment by GIKICoder** [comment]
这个现在不支持.... 之后有时间把backString功能加上

**Comment by wyt666** [comment]
哦，好吧，谢谢

**Comment by GIKICoder** [comment]
目前已经支持表情的backstring的copy

**Comment by wyt666** [comment]
@GIKICoder 好的，我更新一下，谢谢
