### ISSUE TITLE
如何计算行高？

### ISSUE THREAD

**Issue by wqforever** [GIKICoder/GRichLabel#6]
NSMutableAttributedString *config = [GAttributedStringFactory createAttributedStringWithAttributedConfig:layout];

用这个来计算会报错，为什么

**Comment by GIKICoder** [comment]
报什么错？

**Comment by wqforever** [comment]
会崩溃

**Comment by GIKICoder** [comment]
崩溃？贴一些崩溃堆栈

**Comment by wqforever** [comment]
NSMutableAttributedString *config = [GAttributedStringFactory createAttributedStringWithAttributedConfig:layout];
用这个计算行高会崩溃，具体的堆栈信息找不到了，因为没用了
