### ISSUE TITLE
chatTextCell 里选择文字的时候，不能滚动选择超出范围的文字。

### ISSUE THREAD

**Issue by cntrump** [GIKICoder/GRichLabel#7]
微信使用的是 YYText，长文字聊天气泡内容分割成了多个cell，实现了滚动选择，可惜没提交 PR。

**Comment by cntrump** [comment]
YYText demo 的选择模拟了 UITextView，选择的时候把行间的空隙也填充了，视觉上比较舒服。

**Comment by GIKICoder** [comment]
之前想实现来着。 找时间把这个功能实现了。

**Comment by GIKICoder** [comment]
@cntrump  可以更新下代码。已经添加了这2个case的处理。
增加了GRichLabelScrollerAutoSelect  scrollerAutoSelectType属性。默认不开启滚动选择。
可设置  GRichLabelScrollerAutoSelectLine 逐行选择  ， GRichLabelScrollerAutoSelectAll 类似于微信的直接滚动到文本底部。
